# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official lightweight Node.js image
FROM node:lts-alpine AS builder
# Create app directory
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN npm install --ignore-scripts
# Copy source
COPY . .
# Build TypeScript
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app
# Copy built files and production deps
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
# Copy package.json if needed
COPY package.json .

# Default command
CMD ["node", "dist/index.js"]
